### ISSUE TITLE
Using `require` with splitting enabled generates an extra chunk.

### ISSUE THREAD

**Issue by hyrious** [evanw/esbuild#1747]
**Problem:** Using `require` with splitting enabled generates an extra chunk of `__require` as an dependency of all output files.

Or: **Empty common chunks are not collapsed**.

What's that mean? see reproduction below ([or see it live](https://hyrious.me/esbuild-repl/?shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJhLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnJlcXVpcmUlNUNuY29uc29sZS5sb2coJ2EnKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY29uc29sZS5sb2coJ2InKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiU3RCU3RA%3D%3D)):

**Reproduce:**
```js
// a.js
require; // simplified `var __require = ...`,
         // let's just keep the side effects.
console.log('a')

// b.js
console.log('b')
```

```shell
$ esbuild a.js b.js --bundle --format=esm --splitting --outdir=dist
```

```js
// dist/a.js
import "./chunk-BYXBJQAS.js";

// a.js
console.log("a");
```

```js
// dist/b.js
import "./chunk-BYXBJQAS.js"; // <- this line shouldn't exist
                              // as b.js does not depend on `require`
// b.js
console.log("b");
```

```js
// dist/chunk-BYXBJQAS.js
(!!! EMPTY !!!)
// this file actually has an `__require` definition,
// but is tree-shaked after bundling
```

```js
// dist/chunk-BYXBJQAS.js, with --tree-shaking=false
var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
  get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
}) : x)(function(x) {
  if (typeof require !== "undefined")
    return require.apply(this, arguments);
  throw new Error('Dynamic require of "' + x + '" is not supported');
});

export {
  __require
};
```

**Comment by hyrious** [comment]
Looks like it has been fixed in 0.14.5?

**Comment by hyrious** [comment]
Now to reproduce it, you have to having "require" in 2+ files with splitting on: [(live link)](https://hyrious.me/esbuild-repl/?version=0.14.23&mode=build&modules=%5B%5B%22a.js%22%2C%22require+%2F%2F+try+comment+out+this%22%2C1%5D%2C%5B%22b.js%22%2C%22require%22%2C1%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Atrue%7D).

**Comment by tennox** [comment]
Encountered this today, still reproducible:
https://hyrious.me/esbuild-repl/?version=0.14.23&b=e%00a.js%00import+%7B+x+%7D+from+%22.%2Fx.js%22&b=e%00b.js%00import+%7B+x+%7D+from+%22.%2Fx.js%22&b=%00x.js%00export+var+x+%3D+1&o=%7B%0A++%22bundle%22%3A+true%2C%0A++%22format%22%3A+%22esm%22%2C%0A++%22splitting%22%3A+true%2C%0A++%22treeShaking%22%3A+false%2C%0A++%22outdir%22%3A+%22%2F%22%2C%0A++%22allowOverwrite%22%3A+true%0A%7D

**Comment by hyrious** [comment]
@tennox Your link is still using 0.14.23 version of esbuild (you can change the version at to top-right corner). Here's the latest reproduction: https://esbuild.github.io/try/#YgAwLjE5LjEwAHsKICAiYnVuZGxlIjogdHJ1ZSwKICAiZm9ybWF0IjogImVzbSIsCiAgInNwbGl0dGluZyI6IHRydWUsCiAgInRyZWVTaGFraW5nIjogZmFsc2UsCiAgIm91dGRpciI6ICIvIiwKICAiYWxsb3dPdmVyd3JpdGUiOiB0cnVlCn0AZQBhLmpzAGltcG9ydCB7IHggfSBmcm9tICIuL3guanMiAGUAYi5qcwBpbXBvcnQgeyB4IH0gZnJvbSAiLi94LmpzIgAAeC5qcwBleHBvcnQgdmFyIHggPSAx

**Comment by hyrious** [comment]
@esushilnikov Your issue is more like a server configuration issue as empty js chunks are still valid es modules. It is possible that your server does not send valid mime type (like application/javascript) for empty js files.

**Comment by esushilnikov** [comment]
@hyrious, thanks for your feedback and advice.
Yeap, in my case, the main issue with `Content-Type`.
The CDN removes content-type from empty files, and this is the main issue for a browser.
Right now set my focus on the CDN configuration.
p.s. Empty chunks should not be presented inside a bundle.

**Comment by matviienko-pin-up** [comment]
I had the similar issue, but for me the empty chunk was generated when sourceMap was false instead of script optimization.

My team have found that the issue was related with declaration of route path. I mean that we had some enum with routes and we just have changed this to simple const object and this issue has gone

**Comment by matviienko-pin-up** [comment]
I had the similar issue, but for me the empty chunk was generated when sourceMap was false instead of script optimization.

My team have found that the issue was related with declaration of route path. I mean that we had some enum with routes and we just have changed this to simple const object and this issue has gone

**Comment by Obeliccs** [comment]
I had the similar issue, but for me the empty chunk was generated when sourceMap was false instead of script optimization.

My team have found that the issue was related with declaration of route path. I mean that we had some enum with routes and we just have changed this to simple const object and this issue has gone

**Comment by kris-vista** [comment]
Having the same issue with the same file `chunk-BYXBJQAS.js`
It would be helpful to know what this is so I could at least edit my solution and remove whatever this thing is so it doesn't need to be tree shaken

**Comment by MikaelPorttila** [comment]
Having the same issue with an Angular 21 project while I try to import classes from @arcgis/core, I have tried to add the import files as a sideeffect but it doesn't change anything, still getting the empty file when I do a production build with optimization while dev serve using Vite has no problem.

<img width="890" height="122" alt="Image" src="https://github.com/user-attachments/assets/1e965661-b492-4c8a-a09a-573262793b80" />

**Comment by janinternet** [comment]
> Having the same issue with an Angular 21 project while I try to import classes from @arcgis/core, I have tried to add the import files as a sideeffect but it doesn't change anything, still getting the empty file when I do a production build with optimization while dev serve using Vite has no problem.
> 

Having the exact same issue. sourceMap false solves the issue.
