### ISSUE TITLE
Perf issue: npm/yarn download all platform builds!

### ISSUE THREAD

**Issue by AliMD** [evanw/esbuild#2949]
Hi @evanw, thanks to make and publish this great tools.

I have to wait a long time to download all the platform builds every week to update esbuild!
Is there a way to solve this problem?
Thank you in advance.

**Comment by AliMD** [comment]
<img width="1198" alt="Screen Shot 2023-02-24 at 11 53 20 PM" src="https://user-images.githubusercontent.com/697913/221285778-f790419b-6d4c-47af-877a-7b4bd086d883.png">

**Comment by evanw** [comment]
This was a bug with Yarn: https://github.com/yarnpkg/berry/issues/3317. It was fixed in 2021: https://github.com/yarnpkg/berry/pull/3575. You need to use a newer version of Yarn to pick up the fix.

**Comment by AliMD** [comment]
Unfortunately, I still don't use Barry! And I don't have enough time budget for updating right now.

Thanks for the quick response. It's amazing to me that you still have enough time to support and answer questions despite your huge workload. Please, if you get a chance, teach us some tips in the form of a simple article 😄
